### ISSUE TITLE
Extend /plugins/vdr-remote/70-remote-device.rules

### ISSUE THREAD

**Issue by chriszero** [VDR4Arch/vdr4arch#102]
Extending /plugins/vdr-remote/70-remote-device.rules to support iMon Remote

udev info:
```
 looking at device '/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.0/rc/rc0/input7/event5':
    KERNEL=="event5"
    SUBSYSTEM=="input"
    DRIVER==""

  looking at parent device '/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.0/rc/rc0/input7':
    KERNELS=="input7"
    SUBSYSTEMS=="input"
    DRIVERS==""
    ATTRS{name}=="iMON Remote (15c2:0038)"
    ATTRS{phys}=="usb-0000:00:1d.0-1.3/input0"
    ATTRS{properties}=="0"
    ATTRS{uniq}==""
```

Suggesting 
```
SUBSYSTEM=="input", KERNEL=="event[0-9]*", ATTRS{name}=="*dvb*|*DVB*|* IR *|*Remote*", GROUP="vdr" SYMLINK+="input/ir"
```

**Comment by M-Reimer** [comment]
Please try:

`
SUBSYSTEM=="input", KERNEL=="event[0-9]*", ATTRS{name}=="iMON Remote (15c2:0036)", GROUP="vdr"
`

No new symlink, as this would be some distribution specific special thingy. Please use `/dev/input/by-id` or `/dev/input/by-path`. This works on all distributions.

**Comment by CReimer** [comment]
We have a /dev/input/ir symlink. Isn't that already distribution specific.
I think it's best to remove the SYMLINK part from all udev rules.

**Comment by M-Reimer** [comment]
No. /dev/input/ir is pointing to the IR of the *DVB card* on other distributions, too. Actually I've taken this rule from some other distribution in the past. Can't remember from which one though...

**Comment by M-Reimer** [comment]
Actually the whole rule is far from perfect. Would be better to match each device without al those wildchars. Let's keep as is and do new devices "the right way".

**Comment by chriszero** [comment]
Ok, one explicit rule for each device. Will this rules added to the vdr-remote package, or has the user take care of it?

**Comment by M-Reimer** [comment]
Will be added as soon as you give it a try ;)
I don't have the device to check it out...

**Comment by chriszero** [comment]
Works for me.
Second line is the volume knob from the iMon Device (VFD+IR+Knob)

    SUBSYSTEM=="input", KERNEL=="event[0-9]*", ATTRS{name}=="iMON Remote (15c2:0036)", GROUP="vdr"
    SUBSYSTEM=="input", KERNEL=="event[0-9]*", ATTRS{name}=="iMON Panel, Knob and Mouse(15c2:0038)", GROUP="vdr"

**Comment by M-Reimer** [comment]
Fixed in GIT: https://github.com/VDR4Arch/vdr4arch/commit/7f69ddab9523aff9d6ed3ca4c5b511d9ad07e879
