### ISSUE TITLE
Bump Kodi PVR VNSI addon

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#104]
Can you please update VNSI pvr addon to [this git commit](https://github.com/kodi-pvr/pvr.vdr.vnsi/commit/73de793af0eca67170b5a790db42d435c3a07b4d)?

I think it will make it compatible with Kodi 15.1.1 that is actually on Arch Linux ARM.

Thanks in advance :)

---

EDIT: This is just a small protip for you when you're gonna compile it: you have to rename the file
```
addon.xml.in
```
into
```
addon.xml
```
inside `src/pvr.vdr.vnsi/pvr.vdr.vnsi` to make it work. Otherwise you'll get a nasty error that I couldn't localize where it comes from. Maybe this will save some time for you :)

---

EDIT2: Well, I installed it but somehow I cannot see it on the list not. Maybe the PVR 3.0.0 is not compatibile with 15.1.1? Anyway I'm in a situation where, if I install v1.11.3 I cannot get it enabled and working. But If I install the v1.11.4 ( the one I just tryed to compile ) I cannot see it in the list. Really strange, waiting for hint from you...

**Comment by CReimer** [comment]
For some reason they completely broke their Makefiles. With the right files in the right places it seems to work great. Packages for ARM will follow shortly.

**Comment by julianxhokaxhiu** [comment]
Thank you!
