### ISSUE TITLE
[RPi2] Kodi 15.1.1 + VDR 2.2.0 = Lag after some seconds

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#105]
Hi,

I was trying to understand if it is only my issue or if you're having it too. I would like to understand why decoding DVB-S2 signal through VDR on Arch is lagging just after 2 or 3 seconds of playing.

Using the same components ( Kodi, VDR, RPi2, MPG2 codec unlocked ) on OpenELEC is working fine ( no lags, no issues ) while on Arch I get this lag which makes the video out-of-sync with the audio.

Thanks in advance for any help

**Comment by CReimer** [comment]
Hmm, sound for me more like an Arch Linux ARM problem. It works fine with x86_64.

**Comment by julianxhokaxhiu** [comment]
It seems I'm not alone. Probably it's an issue of RPi, I'm actually [trying some config.txt flags](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=101638) and it seems they're again in sync.
