### ISSUE TITLE
vdr 2.3.x for armv7h

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#109]
Is it possible to have it? Even on Testing.

Thank you in advance!

**Comment by CReimer** [comment]
Well, it is possible. 

I stopped compiling right after I found out that my plugin patches for vdr 2.3.1 are not working.
Most likely I'm going to revert a bunch of commits before providing new packages.

**Comment by julianxhokaxhiu** [comment]
Looking forward then :)

**Comment by CReimer** [comment]
Step 1 is done. Reverted all commits with my broken patches. Next up. Reenabling plugins with upstream fixes.

**Comment by julianxhokaxhiu** [comment]
Nice!

**Comment by CReimer** [comment]
Done.
