### ISSUE TITLE
cec-remote plugin not working from plain install - vdr user in group lock needed

### ISSUE THREAD

**Issue by connaisseur** [VDR4Arch/vdr4arch#110]
To make use of the cec-remote plugin the vdr user needs to be added to the "lock" group. The lockdev-package seems to require this.

Added vdr-user to "lock"-group and after a restart CEC commands flowed in an out of the box to the TV set.

Guess a change in vdr.sysuser of the vdr-package should fix this.

**Comment by CReimer** [comment]
You should report this in the Arch bugtracker

Some more information on this:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=728023
https://github.com/Pulse-Eight/libcec/issues/141
