### ISSUE TITLE
skinnopacity

### ISSUE THREAD

**Issue by MajestyIV** [VDR4Arch/vdr4arch#112]
Wäre es möglich skinnopacity mit ins Repo aufzunehmen? Dann wäre VDR4Arch perfekt!

**Comment by olebowle** [comment]
IIRC wird vdr-skinnopacity nicht mehr weiterentwickelt. Du solltest vielleicht mal vdr-skindesigner mit dem Skin nopacity versuchen. Den Skin kannst du direkt im Setup vom Plugin vdr-skindesigner herunterladen.

**Comment by MajestyIV** [comment]
Den habe ich mir schon angesehen. Keep it light fehlt leider als Theme. Ausserdem habe ich das Gefühl, Skindesigner ist auf dem Rpi2 etwas träge.

**Comment by M-Reimer** [comment]
olebowle hat recht. Skinnopacity war schon Bestandteil von vdr4arch. Und wurde rausgenommen, weil vom Entwickler die Kombination "Skindesigner + Skinnopacity" als offizieller "Nachfolger" definiert wurde.

**Comment by M-Reimer** [comment]
Eventuell helfen dir folgende Threads weiter:
http://www.vdr-portal.de/board16-video-disk-recorder/board109-vdr-skins/124530-skindesigner-und-raspberry/
http://www.vdr-portal.de/board16-video-disk-recorder/board109-vdr-skins/p1251075-rpi-2-skins/

Im ersten Thread geht es speziell um das Thema Raspberry und Skindesigner. Wenn du also auch nach Lektüre der Threads noch Probleme hast, dann vielleich dort mal melden.
