### ISSUE TITLE
Update dddvb-dkms

### ISSUE THREAD

**Issue by dahlSTROM** [VDR4Arch/vdr4arch#114]
Could you please update dddvb to the latest 0.9.21 version? Thanks!

https://github.com/DigitalDevices/dddvb/releases/tag/0.9.21

**Comment by CReimer** [comment]
Done. Thanks for reporting

**Comment by dahlSTROM** [comment]
@CReimer I didn't want to open a new issue, but could you update the drivers to 0.9.23? (https://github.com/DigitalDevices/dddvb/releases/tag/0.9.23). Thanks!
