### ISSUE TITLE
vdr-plugin-tvguideng: undefined symbol

### ISSUE THREAD

**Issue by chriszero** [VDR4Arch/vdr4arch#116]
Dez 20 20:11:20 vdr01 vdr[379]: [379] loading plugin: /usr/lib/vdr/plugins/libvdr-tvguideng.so.2.2.0
Dez 20 20:11:21 vdr01 vdr[379]: [379] ERROR: /usr/lib/vdr/plugins/libvdr-tvguideng.so.2.2.0: undefined symbol: _ZN15skindesignerapi11cOsdElement15GetEpgImagePathEv

**Comment by chriszero** [comment]
hmm, ok. Dachte erst das ist ein Fehler der durch neukompilieren verschwindet. Das ist was anderes...

**Comment by CReimer** [comment]
Gut, ich kann das im Moment auch schlecht testen. Das muss noch bis zum Wochenende warten. Dann schaue ich es mir an.

**Comment by CReimer** [comment]
Sollte gefixt sein.
