### ISSUE TITLE
Error Mesage

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#118]
Hi,
bekomme seit gestern folgende Meldung:
Fehler: Die Datenbank von vdr4arch ist inkonsistent: Die Versionsnummern für das Paket vdr-plex stimmen nicht überein
Fehler: Die Datenbank von vdr4arch ist inkonsistent: Die Versionsnummern für das Paket vdr-plex-debug stimmen nicht überein

**Comment by CReimer** [comment]
Ist gefixt. Mein neues Buildsystem läuft dort scheinbar noch nicht richtig sauber. Dadurch wurde das alte vdr-plex Paket nicht gelöscht, sonder nur das neue hinzugefügt. Das gefällt wiederum pacman nicht.

**Comment by utiltiy** [comment]
Danke!
