### ISSUE TITLE
Can't found media-build-experimental-dkms package via pacman

### ISSUE THREAD

**Issue by zofiel** [VDR4Arch/vdr4arch#119]
I try to reinstall this package after a kerne upgrade, but system can't found the package.

I perform a pacman -Sl vdr4arch and the package is not listed too

**Comment by CReimer** [comment]
I dropped it from the repo. I'm unable to compile it, too. AFAIK is this package unmaintained and is no longer compatible with recent kernel version.

**Comment by zofiel** [comment]
One user from this forum post a .diff patch ro resolve the issue.
http://www.vdr-portal.de/index.php?page=Thread&pageNo=10&threadID=124665

I tried It but I don't know how apply that :(

**Comment by zofiel** [comment]
this thread resolve the issue if you want to continue with this driver:

http://www.vdr-portal.de/index.php?page=Thread&postID=1260506#post1260506

Thanks a lot for your help

**Comment by CReimer** [comment]
It works again. Thanks for aquiring this information.
You can find the fix in the vdr-next branch or this commit 8f9bd389899ee89ba004
