### ISSUE TITLE
some problems for vdr-live & restfulapi on arm boxes 

### ISSUE THREAD

**Issue by niedi74** [VDR4Arch/vdr4arch#122]
hi 
i 'm not able since a while to use vdr-live & restfulapi anymore on my ARM box ( armv5) 

Feb 06 09:55:57 NSA325-v2 vdr[9796]: [9796] loading plugin: /usr/lib/vdr/plugins/libvdr-live.so.2.2.0
Feb 06 09:55:57 NSA325-v2 vdr[9796]: [9796] ERROR: /usr/lib/vdr/plugins/libvdr-live.so.2.2.0: undefined symbol: _ZNK3tnt9Urlmapper7mapCompERKNSt7__cxx1112...ESaIcEEES8_
Feb 06 09:55:57 NSA325-v2 vdr[9796]: vdr: /usr/lib/vdr/plugins/libvdr-live.so.2.2.0: undefined symbol: _ZNK3tnt9Urlmapper7mapCompERKNSt7__cxx1112basic_str...ESaIcEEES8_

Feb 06 09:54:57 NSA325-v2 vdr[9784]: [9784] ERROR: /usr/lib/vdr/plugins/libvdr-restfulapi.so.2.2.0: undefined symbol: _ZN6Magick5Image4readERKSs
Feb 06 09:54:57 NSA325-v2 vdr[9784]: vdr: /usr/lib/vdr/plugins/libvdr-restfulapi.so.2.2.0: undefined symbol: _ZN6Magick5Image4readERKSs

is there a possibility to solve this ?

thx
karsten

**Comment by CReimer** [comment]
This happens because of outdated ARM packages.

My ARM build system broke down a while ago and I haven't had the time to set it back up.
But this ticket is a good reminder for me to finally do so.

**Comment by niedi74** [comment]
no worries. 

I tried to build via git and aur. but it didn't  work. 

thanks for your work on this project. 

thx

**Comment by niedi74** [comment]
many thx copperhead, it is working now :)
