### ISSUE TITLE
burn plugin request

### ISSUE THREAD

**Issue by ast261** [VDR4Arch/vdr4arch#126]
Hallo,

ich habe das burn Plugin paketiert.
Kannst du das bitte ins AUR einstellen ?
Zwei Dinge sind mir aufgefallen:

1. Pacman kann die Pakete projectx und lxdvdrip nicht installieren, da sie sich im AUR befinden. Diese konnte ich nur händisch installieren. Wie löst man ein solches Problem in Archlinux ?

2. Im "package" Bereich sollte man evtl. statt "cp" GNU install verwenden. 

[vdr-burn.zip](https://github.com/VDR4Arch/vdr4arch/files/131287/vdr-burn.zip)

**Comment by CReimer** [comment]
Naja. Ich löse das indem ich ein eigenes Repository pflege. Das AUR ist für mich eher zweitrangig. Die Paketqualität dort ist viel zu häufig eine Katastrophe.

Deine Annahme mit dem 'install' ist richtig. Obwohl ich bei ganzen Verzeichnissen auch häufig zu cp greife. Zusätzlich fehlen allerdings noch die chown Befehle für /var/lib/vdr.

Wünschenswert wäre auch, wenn man die Dateien aus /usr/bin fernhalten könnte. Ich schiebe dort nur ungern Sachen hin und wenn ich mich an vdr-burn richtig zurückerinnere, sind das keine Anwendungen, die den Nutzer interessieren. Daher würde ich das bevorzugt nach /usr/lib/vdr/bin packen.

Ich schaue mir dein PKGBUILD morgen mal an und passe es entsprechend an. Wegen projectx und lxdvdrip schaue ich ebenfalls nach.

Ich habe mich um vdr-burn bisher immer gedrückt, weil ich es selbst nicht verwenden werde und es deswegen auch nicht testen kann. Ich habe nichtmal einen DVD Brenner im VDR. Wenn es aber für die funktioniert kann ich immer mit dem Finger auf dich zeigen, wenn es doch nicht funktionieren sollte. :smile:

**Comment by CReimer** [comment]
Implementiert: 4e3aa619dc5cc3b97433b841f44ffe636e3b8eee

**Comment by ast261** [comment]
> Wünschenswert wäre auch, wenn man die Dateien aus /usr/bin fernhalten könnte. Ich schiebe dort nur ungern Sachen hin und wenn ich mich an vdr-burn richtig zurückerinnere, sind das keine Anwendungen, die den Nutzer interessieren. Daher würde ich das bevorzugt nach /usr/lib/vdr/bin packen.

Das Plugin ruft Shell-Skripte auf. Daher sollten die Skripte in einem Pfad liegen, der über die PATH Variable referenziert wird ?

**Comment by ast261** [comment]
> Implementiert:

Mercy 
:+1:
