### ISSUE TITLE
vdr cannot build against systemd-229-2

### ISSUE THREAD

**Issue by knedlyk** [VDR4Arch/vdr4arch#127]
Package systemd-229-2 doesn't contain sdnotify headers, that is why it is impossible to build vdr with "SDNOTIFY = 1" parameter. 
Temporary solution: downgrade to systemd-228.

**Comment by olebowle** [comment]
In systemd-228 the "systemd Daemon Utility Library" (libsystemd-daemon) was marked as deprecated. In 229 libsystemd-daemon.pc is removed. Thus the following patch is required for the vdr Makefile:
```diff
--- a/Makefile
+++ b/Makefile
@@ -95,9 +95,9 @@ DEFINES += -DBIDI
 LIBS += $(shell pkg-config --libs fribidi)
 endif
 ifdef SDNOTIFY
-INCLUDES += $(shell pkg-config --cflags libsystemd-daemon)
+INCLUDES += $(shell pkg-config --cflags libsystemd)
 DEFINES += -DSDNOTIFY
-LIBS += $(shell pkg-config --libs libsystemd-daemon)
+LIBS += $(shell pkg-config --libs libsystemd)
 endif
 
 LIRC_DEVICE ?= /var/run/lirc/lircd
```

**Comment by knedlyk** [comment]
It works! Thanks for the patch.
