### ISSUE TITLE
ffmpeg 3.x

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#128]
Es gab per Pacman ein Update auf ffmpeg 3.x, erfordert ein Rebuild diverser Pakete

**Comment by utiltiy** [comment]
Softhddevice und Markad lassen sich in der VBox bei mir nicht bauen mit ffmeg 3.x

**Comment by mafe** [comment]
There is an extra package, now, that runs with the current built:

ffmpeg2.8

I think, path to header files must be adjusted: /usr/include/ffmpeg-2.8/...

**Comment by utiltiy** [comment]
Did you mean to add the Package "ffmpeg2.8" in PKGBUILD as "depends"?

**Comment by mafe** [comment]
Yes, but in order to compile, you will have to adjust paths to /usr/include/ffmpeg-2.8/...

But it will run with the current compiled binary from the vdr4arch repo, anyway.

**Comment by utiltiy** [comment]
OK

I ignore the update from ffmpeg, libx264, mpv and wait of a solution from Copperhead :)

**Comment by CReimer** [comment]
OK. It's fixed for now.
ffmpeg developers seem to have the urge to break their API with every release.
Therefore we stay with ffmpeg 2.8 to work around this.
