### ISSUE TITLE
VDR only runs from the terminal and in foreground

### ISSUE THREAD

**Issue by rabejens** [VDR4Arch/vdr4arch#129]
I installed VDR4Arch and got it running somehow. I am using softhddevice with VDPAU. The problem is: It only works when starting from a terminal. So, when I start xterm and type vdr, VDR runs. However, as soon as I try to start it in background (e.g. vdr&), I only get a black screen and VDR has to be killed with -9. The same happens when I simply put "exec vdr" into .xinitrc of my vdr user.
When using systemctl start vdr, I only get audio.

What am I doing wrong?

**Comment by rabejens** [comment]
Made the topic more specific

**Comment by rabejens** [comment]
I now reinstalled the machine and exactly followed the steps here. Now, X.org autostarts correctly, but VDR not.

My journal says:
`Feb 28 16:33:15 windbox vdr[450]: freeglut (-display 0:0): failed to open display ''`

What am I missing?

**Comment by utiltiy** [comment]
Is this a normal installation or vbox?

**Comment by rabejens** [comment]
It is a normal installation.

**Comment by rabejens** [comment]
I now got it to work with xineliboutput, sort of, but it doesn't seem to scale the picture - The picture is in its original siye in the top left corner, and nothing like fullscreen or geometry works.

**Comment by utiltiy** [comment]
I us SHD, it works fine

**Comment by CReimer** [comment]
Freeglut doesn't find the right display? That's strange.
softhddevice works here fine, too.

**Comment by CReimer** [comment]
That's an upstream problem introduced with the opengl OSD.
