### ISSUE TITLE
vdr-distributedvideodirectory

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#131]
Kann man das Plugin mit aufnehmen?
http://www.vdr-portal.de/board17-developer/board21-vdr-plugins/p1266918-distributedvideodirectory-f%C3%BCr-vdr-2-2-0-und-neuer-erste-testversion/#post1266918

**Comment by CReimer** [comment]
Könnte man. Mache ich aber erst, wenn es auch eine ordentliche Projektseite gibt.
Oder zumindest ein Github-Projekt
