### ISSUE TITLE
diverse Plugins

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#132]
Hallo,
eventuell kannst Du mal die folgenden Plugins auf aktuellen Stand bringen:
- vdr-dbus2vdr: Lokale Version (29-1) ist neuer als vdr4arch (26-2)
- vdr-live: Lokale Version (1:0.3.0_22_g869ac69-1) ist neuer als vdr4arch (1:0.3.0_21_g6ea279a-2)
- vdr-pulsecontrol: Lokale Version (0.1.9-1) ist neuer als vdr4arch (0.1.7-1)
- vdr-recsearch: Lokale Version (0.3.7-1) ist neuer als vdr4arch (0.3.5-7)
- vdr-restfulapi: Lokale Version (2.6.0_23_gd002343-1) ist neuer als vdr4arch (0.2.5.0-3)
- vdr-trayopenng: Lokale Version (1.0.2-1) ist neuer als vdr4arch (1.0.1-9)

**Comment by CReimer** [comment]
Danke. Ist auch alles drin.

**Comment by utiltiy** [comment]
Danke schön :)

**Comment by utiltiy** [comment]
Was ich noch mitteilen wollte. Ich habe das Live-Plugin soweit angepaßt dass die Spalten passen und bei Aufnahmen, wenn vorhanden, die EPG Images gezeigt werden. Hast Du Interesse an diesem PKGBUILD? Sind 2 Patche soweit ich das im Kopf habe.
