### ISSUE TITLE
oscam package is missing file "oscam-remove-sslv3.diff"

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#134]
Can you please push it? Thanks in advance :)

**Comment by utiltiy** [comment]
You can also deactivate the SSL option before you compile with the same effect.

**Comment by CReimer** [comment]
Yes you can. But you loose the SSL feature completely. With my patch just SSLv3 is gone.

**Comment by julianxhokaxhiu** [comment]
I'll wait for the official team to migrate to TLS, but meanwhile the patch is perfect :) Thanks again!
