### ISSUE TITLE
pacman -Syu => Fehler

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#135]
Fehler: oscam: Erforderliche Signatur fehlt
Fehler: poco: Erforderliche Signatur fehlt
Fehler: vdr-systeminfo: Erforderliche Signatur fehlt
Fehler: Konnte den Vorgang nicht durchführen (Erforderliche Signatur für Paket fehlt)

**Comment by CReimer** [comment]
Du bist jetzt schon der vierte, der mich darauf hinweist.
Wie sich herausstellt habe ich in meinem Buildsystem versehentlich die Signaturfunktion abgestellt.
Das muss natürlich Chaos verursachen.

Ist gefixt
