### ISSUE TITLE
poco 1.7.1

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#136]
Irgendwas paßt da nicht:
Pakete (1) poco-1.7.1-1

Gesamtgröße der installierten Pakete:   18,51 MiB
Größendifferenz der Aktualisierung:  -11,47 MiB

Wenn ich es installiere startet der VDR nicht mehr.

> Mär 20 22:59:38 vdr04 vdr[673]: [673] ERROR: libPocoNet.so.30: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

**Comment by CReimer** [comment]
Mit welcher Architektur passiert das?

**Comment by utiltiy** [comment]
amd64

**Comment by CReimer** [comment]
Fixed: c3469abd6ae23ff23bfefb2b856bea90b44355e0
