### ISSUE TITLE
HD Channels support / X264 Codec support?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#141]
Hi,

I'm trying to watch `Rai 1 HD` channel today but it doesn't work at all. I tested the latest version of `tvheadend-git` AUR package within the same channel, and it works out of the box.

Does VDR 2.2.0 ( your latest package ) support HD channels? Am I missing something? Maybe a library which vdr is not triggering as optional or required?

Thanks in advance!

**Comment by M-Reimer** [comment]
HD channels should work. I did a quick revision of all packages in vdr-stable branch. Please do a full rebuild (repo-make). Some packages will be missing now but may reappear in future. Which PVR addon do you use in Kodi? Or do you plan to use VDR without the Kodi frontend?

**Comment by julianxhokaxhiu** [comment]
Forgot to update this ticket, actually HD Channels are working now so everything is fine. I'm not able to recognize atm what was missing before, but with the stock VDR built inside Creimer repo's it works :)

Thanks for the support anyway!
