### ISSUE TITLE
VDR Zapcockpit

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#142]
Hallo,
ist es in der Planung den VDR dafür zu patchen und das Feature zur Verfügung zu stellen?

**Comment by CReimer** [comment]
Nein, der VDR bekommt keine weiteren Patches. Es sind jetzt schon zu viele.

Ich versuche mit den Paketen so nah wie möglich an den Arch Linux Richtlinien zu bleiben. Und diese sagen relativ deutlich, dass es nicht die Aufgabe des Distributors ist irgendwelche Patches anzuwenden. Einzige Ausnahme sind Backports zum Schließen von Sicherheitslücken oder zum Fixen von groben Bugs.
