### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by behroozramezani** [VDR4Arch/vdr4arch#143]
I install vdr and softhddevice. i run vdr command 
``vdr -v ~/Videos -P "softhddevice -v va-api `-f"`
vdr run and close. i see this error
`[behrooz@Lenovo-G500 ~]$ vdr -v ~/Videos -P "softhddevice -v va-api -f"
libva info: VA-API version 0.39.2
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
Segmentation fault (core dumped)
How can i fix this issue?

**Comment by M-Reimer** [comment]
VA-API is not tested that much. All I can tell is that VDPAU works well. Please try a rebuild of the softhddevice plugin just to be sure it is linked with the correct VA-API version.

**Comment by CReimer** [comment]
Whatever the reason is. If it's not fixed by the rebuild (commit 40560462ca23c464cc36ef4b66d1b87ac9cab27a) it's not a problem with VDR4Arch. You should report it upstream then.

**Comment by zussel** [comment]
I've the same issue at my environment and also believe it isn't a vdr4arch issue. How can I use the debug library and access the core file (can't find it)?

**Comment by CReimer** [comment]
For every package there's also a -debug package in the repository. Install vdr-debug and vdr-softhddevice-debug and you will find the coredump with systemd's coredumpctl.
