### ISSUE TITLE
vdr-softhddevice + recent lib glew update --> breaks vdr

### ISSUE THREAD

**Issue by connaisseur** [VDR4Arch/vdr4arch#144]
Recent lib glew update to glew-2.0.0-1 from standard arch repo breaks vdr-softhddevice.

Even by recompilation of vdr-softhddevice + glew-2.0.0-1 I was not able to receive a Picture von VDR.

**Comment by tmn505** [comment]
As temporary workaround You can create a symlink: libGLEW.so.1.13 -> libGLEW.so.2.0.0. Worked out for me without rebuild.

**Comment by CReimer** [comment]
Fixed with commit 40560462ca23c464cc36ef4b66d1b87ac9cab27a
