### ISSUE TITLE
vdr4arch vs. aur

### ISSUE THREAD

**Issue by kaffeekanne** [VDR4Arch/vdr4arch#145]
Plant ihr/du AUR und vdr4arch synchron zu halten? Setze gerade nach und nach einen neuen VDR auf und hatte schon bei SoftHDDevice und Streamdev Probleme. Ersteres lief mit den OpenGL-OSD-Patches von louis nicht, letzteres installierte, aber die Versionierung passt nach der Installation nicht, sodass es mir immerwieder von yaourt zur installation angeboten wird.

Ich will gar nicht groß auf die Fehler eingehen. Mir stellt sich nur die Frage, wie ich mein Setup warte. Eigentlich brauche ich kein vorkompiliertes Repo, funktionierende PKGBUILDs und kompilieren lassen ist völlig ok, zumal als Clients noch ARM-Geräte ins Spiel kommen, die VDR4Arch nicht mehr abdeckt.

Grüße

**Comment by CReimer** [comment]
Ohh, ja. Das AUR habe ich ganz vergessen. Spätestens am Wochenende werde ich die Zeit haben, dass wieder anzugleichen.

**Comment by niedi74** [comment]
wie sieht es mit dem builds für die ARM  aus ?

danke

**Comment by M-Reimer** [comment]
Ich gehe davon aus, die wirst du ab dann selber machen müssen. ARM war immer ein kompliziertes Thema. Bauen vom schnellen PC aus hat nie so richtig funktioniert und selbst die schnellste ARM-Hardware, die erschwinglich ist, baut gefühlt ewig an den vdr4arch-Paketen.

Packe dir repo-make auf die ARM-Plattform deiner Wahl. So kannst du dir mit einem einzigen Befehlsaufruf dein eigenes Repository aufbauen.

**Comment by niedi74** [comment]
ok, danke. 
das bekomme ich schon hin. habe ich ja früher auch mit dem git gemacht  ( ist ja alles da und gut beschrieben) . ich brauch ja auch nicht so viele Pakete

**Comment by CReimer** [comment]
Das trifft es schon ziemlich. Der komplette VDR4Arch Tree baut pro ARM-Architektur weit über 5 Stunden auf einem Cubieboard 2 mit angeschlossener SATA Festplatte.
Ich orientiere mich damit jetzt wieder mehr an den Architekturen, die Arch Linux mitliefert. i686 und x86_64

Das heißt aber nicht, dass bei Problemen mit ARM nicht geholfen werden kann. Die Hardware steht hier bereit und nötige Änderungen an den PKGBUILDs werden auch weiterhin für die ARM Architektur unterstützt und auch bei Bedarf eingefügt.

**Comment by niedi74** [comment]
danke

**Comment by CReimer** [comment]
Das AUR ist jetzt wieder auf dem gleichen Stand wie dieses Repository
