### ISSUE TITLE
Neue Version von cecremote

### ISSUE THREAD

**Issue by kaffeekanne** [VDR4Arch/vdr4arch#149]
Das cecremote-Plugin hat eine neuere Version. 1.4. Wenn ich das im aktuellen PKG-Build ändere baut es ordnungsgemäß, der TV sieht trotzdem keine CEC-Geräte.

Kurzer check ergibt:
`[alarm@alarmpi ~]$ cec-client  
cec-client: error while loading shared libraries: libp8-platform.so.2.0: cannot open shared object file: No such file or directory`

p8-platform ist Version 2.1
libcec-rpi ist Version 3.1
libcec ist Version 4.0

Bin mit den Interna nicht ganz vertraut. als cec-Bibliothek habe ich libcec-rpi aus dem alarm-Repository installiert. Irgendwo gibt es da noch Abhängigkeitsprobleme. Bis zu einem Update vor ein Paar Tagen lief alles super.

**Comment by M-Reimer** [comment]
Im "engeren VDR4ARCH-Team" nutzt hier keiner CEC. Wir sind also auf einen funktionierenden Pull-Request angewiesen der von jemandem getestet wurde, der die nötige Hardware-Konfiguration benutzt. Am liebsten natürlich (auch) mit x86_64 getestet.

**Comment by kaffeekanne** [comment]
Ich schau mir das mal an. Es gibt einen Fix im GIT-Repository von cecremote, dazu müsste man master bauen und nicht die getaggte Version 1.4.0. Soweit die Theorie. Kann aber nur auf dem Raspberry Pi bauen und testen, mangels CEC-Hardware an x86_64-Systemen.

**Comment by M-Reimer** [comment]
Bitte das angepasste Makefile ausprobieren. Dieses konkrete Problem sollte damit gelöst sein. Wenn dein Problem damit gelöst ist, dann bitte das Issue direkt zumachen. Danke.

**Comment by M-Reimer** [comment]
Ich mache erstmal zu. Wenn es noch Probleme gibt, dann bitte upstream melden. Der aktuell verfügbare Patch ist jetzt integriert und zumindest Kompilieren ist damit wieder möglich.
