### ISSUE TITLE
vdr-sxfe: error while loading shared libraries: libcec.so.3

### ISSUE THREAD

**Issue by tinitussi** [VDR4Arch/vdr4arch#150]
Hallo,
wenn ich 
vdr-sxfe 
bekomme ich die Fehlermedlung:
vdr-sxfe: error while loading shared libraries: libcec.so.3: cannot open shared object file: No such file or directory
ebenso bei:
vdr-fbfe 
vdr-fbfe: error while loading shared libraries: libcec.so.3: cannot open shared object file: No such file or directory

**Comment by kaffeekanne** [comment]
Sollte das gleiche Problem sein wie bei #149 .

Die aktuelle Version von libcec ist 4. Plugins, die hart auf 3 linken müssen neu gebaut werden. Da hängt aber ein ganzer Rattenschwanz dran. Bin selbst noch nicht dazu gekommen es mir mal näher anzusehen.

**Comment by M-Reimer** [comment]
Ich mache hier mal zu. Das gesamte Problem "CEC" dann bitte in #149 diskutieren.

**Comment by M-Reimer** [comment]
xineliboutput scheint mir doch ein eigenes Problem zu sein. Ich nutze xineliboutput auf meinem Linux-Desktop um remote schneiden zu können. Ich bin gerade an dem Problem dran, aber so wie das für mich aussieht wird die Lösung vorerst sein, CEC komplett zu deaktivieren. Patches tief im Sourcecode sind Aufgabe des Entwicklers der entsprechenden Software und ich selber habe keinen Bedarf an CEC weshalb sich das Interesse, das in Tiefe zu analysieren, in Grenzen hält.

**Comment by M-Reimer** [comment]
Fixed: https://github.com/VDR4Arch/vdr4arch/commit/29a8f700d52503c03b48345119c2bb701cc97fc6
libcec ist jetzt aus solange bis upstream ein Fix eingecheckt wird. Wer hier bedarf hat, darf auch gerne upstream ein Ticket eröffnen: https://sourceforge.net/p/xineliboutput/bugs/
Hier mache ich jetzt zu weil das distributionsspezifische Problem damit erledigt ist.
Ach ja: PKGBUILD bitte selber kompilieren. Bis es passende Binaries gibt kann sich etwas ziehen.
