### ISSUE TITLE
Rebuild graphlcd-base

### ISSUE THREAD

**Issue by freaknils** [VDR4Arch/vdr4arch#151]
Since libvncserver was updated to version 0.9.11-1 on upstream, the graphlcd package needs to be rebuild.
Because of there is no PKBUILD in your git repo, I am not able to build it by my self. Please rebuild it in your vdr4arch repo!

Thanks!

**Comment by CReimer** [comment]
Thanks. A new package is uploading to the repository at the moment and the AUR package is now also up-to-date.
