### ISSUE TITLE
Channelscan package based on old reelchannescan

### ISSUE THREAD

**Issue by knedlyk** [VDR4Arch/vdr4arch#152]
Please take a look on channelscan package based on old reelchannelscan https://bitbucket.org/ua0lnj/channelscan. It is way best than the vdr-wirbelscan. Sample PKGBUILD is there: http://pastebin.com/8ubRnp6b

**Comment by CReimer** [comment]
This sounds promising. But there's no stable release tagged right now.
I'll keep this issue open as a reminder to check back from time to time.

**Comment by dreamvdrbox** [comment]
Hi
missing one file

http://pastebin.com/Js3tzDDi

**Comment by knedlyk** [comment]
Please create a text file with the name "50-channelscan.conf" with the only one string:
`[channelscan]`
That's it :)

**Comment by dreamvdrbox** [comment]
Now is okay but has problems! 
Serach Mode: Manual scan is ok,  but auto mode it's not okay, 
I get a message : Scanning aborted 
DiSEqC  is disabled.

**Comment by knedlyk** [comment]
You can report this issue to https://bitbucket.org/ua0lnj/channelscan . Also you can try the following trick: enable diseqc, create a file diseqc.conf in /var/lib/vdr/ with the currently using satellite parameters, something like:
```
# Sirius  LNB 1
S4.8E 11700 V 9750 t v W15 [E0 10 38 F0] [E1 10 38 F0] W15 t
S4.8E 99999 V 10600 t v W15 [E0 10 38 F1] [E1 10 38 F1] W15 T
S4.8E 11700 H 9750 t V W15 [E0 10 38 F2] [E1 10 38 F2] W15 t
S4.8E 99999 H 10600 t V W15 [E0 10 38 F3] [E1 10 38 F3] W15 T
```
and then try to rescan, it should work.
