### ISSUE TITLE
  VDR PKGBUILD: "sed -i '/define DEPRECATED_VIDEOSYSTEM/d' device.h" breaks softhddevice and rpihddevice

### ISSUE THREAD

**Issue by bsg75** [VDR4Arch/vdr4arch#155]
Hi,

die im Betreff genannte Zeile im VDR-2.2.0 PKGBUILD sorgt bei mir dafür, dass sowohl rpihddevice und softhddevice nicht mehr funktionieren, weil ich diese selbst mit makepkg kompiliere.

Beim rpihddevice ist das OSD verzogen und es kommt kein Bild.
Beim softhddevice kommen wegen OSD noch Bild, dafür aber folgende Fehlmeldung:
Mär 06 13:56:15 vdr vdr[19223]: [19223] OSD size changed to 0x0 @ -nan

Im vdr-portal habe dazu einen Thread aufgemacht mit mehr Details:
http://www.vdr-portal.de/board16-video-disk-recorder/board99-distributionen/p1286983-vdr4arch-rpihddevice-kein-bild/#post1286983

Der Fix ist einfach: Die Zeile "sed -i '/define DEPRECATED_VIDEOSYSTEM/d' device.h" aus dem PKGBUILD entfernen.

Beste Grüße
Christian

**Comment by M-Reimer** [comment]
Das ist eigentlich kein Fix sondern ein Workaround. Die Idee war es eben genau solche Plugins "crashen" zu lassen.
Gibt es denn schon Patches die das entsprechende Problem in softhddevice bzw. rpihddevice fixen?

**Comment by CReimer** [comment]
Ich kann in softhddevice keinen Zusammenhang feststellen. Die alte GetVideoSystem Funktion wird dort nicht verwendet.

**Comment by CReimer** [comment]
Und auch in rpihddevice wird die betroffene Funktion nicht genutzt.

**Comment by bsg75** [comment]
Ich habe noch weiter debugged, weil ich eben auch keinen Call zu GetVideoSystem weder in SoftHDDevice noch in rpihddevice gefunden habe.

Das Problem trifft auf, wenn ich nicht mit repo-make alles neu baue, sondern nur einzelne Pakete mit makepkg.
Wenn jetzt vdr ohne GetVideoSystem-Symbol gebaut wurde, die von cDevice-abgeleiteten Plugins aber noch mit GetVideoSystem, dann scheint das Problem aufzutreten.

Damit können wir den Bug wieder schließen?

**Comment by bsg75** [comment]
Ist eigentlich logisch, dass die Plugins neu kompilieren müssen, wenn sich API/ABI ändern.
Sorry, da war ich übereifrig, aber ich echt lange an dem Problem gesessen ...
