### ISSUE TITLE
VDR 2.3.3

### ISSUE THREAD

**Issue by emilsvennesson** [VDR4Arch/vdr4arch#157]
Hi! 

VDR developer version 2.3.3 has been released and it'd be nice to have it available in vdr4arch-testing. :-)

Also, vdr-plugin-ddci2 has been updated to include MTD support! https://github.com/jasmin-j/vdr-plugin-ddci2/blob/master/HISTORY

**Comment by CReimer** [comment]
VDR 2.3.3 is there since yesterday. And the new version of vdr-plugin-ddci2 is uploading right now.

Thanks.
