### ISSUE TITLE
vdr standalone after crash unable to connect to X

### ISSUE THREAD

**Issue by vrabac** [VDR4Arch/vdr4arch#159]
I am using VDR standalone with vdr-xorg system unit. But after crash, in my case vdr-softhddevice in combination with newest ffmpeg 3.3, VDR (softhddevice) is not able to connect to X server. Seems like session is locked or VDR is restarted to fast before X start again. I am not sure if X server need to to be restarted at all.

Here is log:

> vdr01 systemd[1]: vdr.service: Main process exited, code=killed, status=6/ABRT
> vdr01 systemd[1]: x@vt7.service: Unit not needed anymore. Stopping.
> vdr01 systemd[1]: vdr.service: Unit entered failed state.
> vdr01 systemd[1]: vdr.service: Failed with result 'signal'.
> vdr01 systemd[1]: Stopping X on vt7...
> vdr01 systemd[1]: vdr.service: Service hold-off time over, scheduling restart.
> vdr01 systemd[1]: Stopped Video Disk Recorder.
> vdr01 x-daemon[6576]: (II) Server terminated successfully (0). Closing log file.
> vdr01 systemd[1]: Stopped X on vt7.
> vdr01 systemd[1]: Starting Video Disk Recorder...
> vdr01 vdr[6915]: [6915] VDR version 2.3.4 started
> vdr01 vdr[6915]: [6915] switched to user 'vdr'
> vdr01 vdr[6915]: [6915] codeset is 'UTF-8' - known
> vdr01 vdr[6915]: [6915] override character table is 'ISO-8859-15'
> vdr01 vdr[6915]: [6915] found 28 locales in /usr/share/locale
> vdr01 vdr[6915]: [6915] loading plugin: /usr/lib/vdr/plugins/libvdr-softhddevice.so.2.3.4
> vdr01 vdr[6915]: [6915] loading /var/lib/vdr/setup.conf
> vdr01 vdr[6915]: [6915] loading /var/lib/vdr/sources.conf
> ......
> ......
> vdr01 vdr[6915]: video: Can't connect to X11 server on ':0

**Comment by CReimer** [comment]
It's obvious from your logs what happens. VDR dies for whatever reasons and systemd detects that x@vt7.service is no longer necessary and stops it. That's the normal behaviour for a 'Wants' relation between two services. VDR gets restarted and so does x@vt7.service. Everything fine on this end.

In my opinion it's softhddevices's fault.

Unfortunately there are only two options here. Either we keep this issue open until someone finds a good solution for this or we just close it as won't fix.

There are only two maintainers of VDR4Arch and @M-Reimer and myself use our HTPC systems for Kodi and VDR as backend only. Our whole focus is on Kodi for quite some time now as neither of us believe in a future for VDR as standalone application.

Linear television is an outdated concept and will inevitably be superseded by video on demand services or similar online services. 

Kodi is open to this. VDR is not.

**Comment by M-Reimer** [comment]
As @CReimer already mentioned, I also no longer have a system to test "VDR standalone" with.
We already had this problem with https://github.com/VDR4Arch/vdr4arch/issues/121 Thanks again to @joukewitteveen for working out a solution for the problem and to @olebowle for testing.
But I had a short look at your log and it is interesting that there are several mentionings about stopping the X server but never a startup of a new server is logged.
My guess is, that the X server either never really stops or stops too slow. If it stop too slow, then a second one will be started which is no longer ":0" but ":1" and VDR can't connect to this new one as it will try to connect to :0
I can think of two solutions:
- Either get the server to keep running. This means that either systemd has to wait longer before killing the X server or VDR has to be restarted faster. There is a "hold-off" time mentioned. I guess that this maybe can be configured somewhere to make VDR restart *immediately*.
- Or get the X server stopped faster so it is down before the second startup attempt of VDR happens.

Just a few thoughts where someone else may try to work something out. I'm not able to work on this one.

**Comment by CReimer** [comment]
There don't seem to be any new developments regarding this issue. I'm closing this now. Feel free to reopen this issue when necessary.
