### ISSUE TITLE
vdr 2.3.3+ compilation after update of vdr-portal

### ISSUE THREAD

**Issue by kaffeekanne** [VDR4Arch/vdr4arch#163]
Since the makeover of vdr-portal.de links to patches are not working, also mainmenuhooks. I can not provide a pull-request, but removing this patch, compiles VDR (2.3.8) just fine. Maybe some Plugins need a checkup too. Haven't tried stable vdr, since it needs patching to compile with gcc 7.

**Comment by M-Reimer** [comment]
Maybe the best solution is to actually mirror the patches (maybe with a reference to the Forum thread in the patch).
Will have to recompile everything in the future anyway as I'm working on a new "repo-make" version, but I'm currently still stuck with some broken Arch Linux script stuff that makes it impossible for me to build in a chroot environment...

**Comment by kaffeekanne** [comment]
Is mainmenuhooks that important? I read some time ago, that it might be trown out in future releases anyway. I'm not using prebuilt binaries od vdr4arch, just using the PKGBUILDs. Earlier directly from aur which was very convinient, but outdated nowadays. Is there a way to help you checking some PKGBUILDs? I'm building directly without chroot and need to dig into some plugins anyway in the coming days.

**Comment by kaffeekanne** [comment]
Is mainmenuhooks that important? I read some time ago, that it might be trown out in future releases anyway. I'm not using prebuilt binaries od vdr4arch, just using the PKGBUILDs. Earlier directly from aur which was very convinient, but outdated nowadays. Is there a way to help you checking some PKGBUILDs? I'm building directly without chroot and need to dig into some plugins anyway in the coming days.

**Comment by CReimer** [comment]
No. MainMenuHooks isn't important at all. It's just the last remnant of the big and clunky Extensionpatch. It allows plugins to repace VDR's own mainmenu entries. extrecmenu and epgsearch are using it.

About the AUR packages. I know that they are outdated. That's because I usually forget to run my AUR upload script. It should be up-to-date in the next few minutes.

**Comment by kaffeekanne** [comment]
Thanks for updating AUR, as much as i appreciate your work/repo, i think AUR is the place for well maintained PKGBUILDs, as it integrates perfectly with common Arch helpers like pacaur and yaourt. Otherwise keeping track of updates brings you back to good old Windows times.

**Comment by CReimer** [comment]
Fortunately only the URL changed. The actual attachment ids stayed the same. Which rises the question why the administrator of vdr-portal.de didn't just add a redirection rule.

Nevertheless. It's now back in working order :smile:
