### ISSUE TITLE
VDR4Arch Repo creimer.net broken?

### ISSUE THREAD

**Issue by freaknils** [VDR4Arch/vdr4arch#169]
Hi, I use your VDR4Arch repo at creimer.net sinc a few days there seems to be a redirect error.
Everytime I call it, I am redirected to https://.c-reimer.de/.

It seems that the webserver is missconfigured. Will it be online soon?

**Comment by CReimer** [comment]
Sorry for that. Something went wrong while switching the SSL certificate. It's working again.

**Comment by freaknils** [comment]
No problem.
Thanks for your work!
