### ISSUE TITLE
vdr-epgsearch: Erforderliche Signatur fehlt

### ISSUE THREAD

**Issue by tinitussi** [VDR4Arch/vdr4arch#170]
vdr-epgsearch-1:2.3.1.r46.g5887e0a-1
Grüße und Danke

**Comment by CReimer** [comment]
English:
My build system is now working on my webserver. So there's no human interaction from me anymore.

For security reasons I started enabling HTTPS on my server. That way you can still be 100% sure, that you get the packages from my server without 3rd party intervention.

The automated build script on my server periodically checks this repository also via HTTPS for new commits and start compiling them. Only @M-Reimer and myself are allowed to push here. That way I think we still have some sort of security.

To work around the pacman error message please set replace your vdr4arch section in /etc/pacman.conf with this

```
[vdr4arch]
 Server = https://c-reimer.de/vdr4arch/repos/$repo/os/$arch
 SigLevel = Never
```

I'll update the wiki accordingly.

Deutsch (German): 
Mein Buildsystem arbeitet jetzt auf meinem Webserver. Da ist also kein Kontrolle durch mich direkt mehr vorhanden.

Aus Sicherheitsgründen können die Daten jetzt mit HTTPS von meinem Server abgerufen werden. Auf diese Weise kannst du immernoch 100% sicher sein, dass die Pakete von meinem Server stammen und kein Dritter eingegriffen hat.

Das automatische Buildsystem prüft in regelmäßigen Abständen dieses Git-Repository über HTTPS nach neuen Commits und kompiliert diese. Nur @M-Reimer und ich können hier direkt pushen. Dadurch ist immernoch eine Sicherheit gegeben.

Um die Meldung in Pacman loszuwerden ändere bitte deinen vdr4arch Bereich in der /etc/pacman.conf in das hier um:

```
[vdr4arch]
 Server = https://c-reimer.de/vdr4arch/repos/$repo/os/$arch
 SigLevel = Never
```

Ich werde das Wiki entsprechend anpassen.
