### ISSUE TITLE
vdr-wirbelscan: Version 2017.06.04 verfügbar

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#183]
Link:
http://wirbel.htpc-forum.de/wirbelscan/vdr-wirbelscan-dev-2017.06.04.tgz

Nötig für 2.4.0 obwohl als "dev" bezeichnet

**Comment by utiltiy** [comment]
Das Paket enthält keine *.so im Repo

https://creimer.net/vdr4arch/repos/vdr4arch/os/x86_64/vdr-wirbelscan-2017.06.04-8-x86_64.pkg.tar.xz

**Comment by CReimer** [comment]
Fixed in  619e2c2
