### ISSUE TITLE
vdr-markad does not build against ffmpeg 4.x

### ISSUE THREAD

**Issue by mafe** [VDR4Arch/vdr4arch#197]
Dependency changed to ffmpeg3.4
Therefore, also the header files have to be included from:

```
/usr/include/ffmpeg3.4
```

This could be done by appending vdr-markad-newmakefile.diff
```
+INCLUDES += /usr/include/ffmpeg3.4
```

**Comment by M-Reimer** [comment]
On a "valid" build system you should only have one ffmpeg installed.

But I'll have a look at this as soon as I find the time.

Most probably this also means removing the "newmakefile" patch at all as markad, so far, never migrated to the "new Makefile" and it is not job of vdr4arch to maintain a new Makefile.

**Comment by M-Reimer** [comment]
I had a look at this one and I don't know why you think that the dependency has changed to "ffmpeg3.4". For me it is still configured to build against the latest version:
https://github.com/VDR4Arch/vdr4arch/blob/vdr-stable/plugins/vdr-markad/PKGBUILD#L14
But I haven't checked if it builds and I also don't use this plugin.
Please give some more info.

**Comment by mafe** [comment]
This applies to markad-standalone, which is in subfolder <srcdir>/vdr-plugin-markad/command
The currently used ffmpeg package uses version 4.0.2-1 from the extra repository and is incompatible to vdr-markad.
markad-standalone needs 3.x versions (aur/ffmpeg3.4 3.4.2-1), in order to compile.

vdr-markad-standalone-ffmpeg3.4-compat-fix.diff:
`
diff --git a/command/Makefile b/command/Makefile
index 6a445d0..c878e3c 100644
--- a/command/Makefile
+++ b/command/Makefile
@@ -31,7 +31,7 @@ ifdef WITH_OLD_FFMPEG_HEADERS
 endif
 
 
-INCLUDES += $(shell $(PKG-CONFIG) --cflags $(PKG-INCLUDES))
+INCLUDES += $(shell $(PKG-CONFIG) --cflags $(PKG-INCLUDES)) -I/usr/include/ffmpeg3.4
 LIBS     += $(shell $(PKG-CONFIG) --libs $(PKG-LIBS)) -pthread
 
 ### The object files (add further files here):
`

**Comment by M-Reimer** [comment]
This is not a proper fix. To actually fix this issue, someone has to create a patch to make markad build against ffmpeg 4.x

**Comment by M-Reimer** [comment]
I've found the following patches:
https://svnweb.freebsd.org/ports/head/multimedia/vdr-plugin-markad/files/
I won't have a look into this as I don't use markad, but maybe someone else wants to give the patches a try.
Please try to use as less patches as possible! Only apply the patches really needed! If you submit a pull request, patching the minimal patch set, I'll accept it.

**Comment by M-Reimer** [comment]
I've adapted the relevant parts of the FreeBSD patches.
Markad compiles now, but I won't test if it actually works.
