### ISSUE TITLE
Publish latest vdr 2.4.0-5?

### ISSUE THREAD

**Issue by jansohn** [VDR4Arch/vdr4arch#200]
Any reason why vdr4arch is not offering the latest version vdr 2.4.0-5 (https://github.com/VDR4Arch/vdr4arch/blob/vdr-stable/vdr/PKGBUILD)?

    $ pacman -Sl vdr4arch
    vdr4arch vdr 2.4.0-3 [installed]

**Comment by M-Reimer** [comment]
I can't speak for Copperhead, but as far as I'm aware, you shouldn't expect to get updated binaries anytime soon.

Use the PKGBUILD's to compile your own packages.

**Comment by jlp2** [comment]
Maybe there is the opportunity to submit the PKGBUILD's to the AUR, so that we can use the aurhelpers to install and update the vdr-installation.

**Comment by M-Reimer** [comment]
This would require that we at least get the "auto-upload" scripts working again to automatically upload the github repo to AUR.

**Comment by jansohn** [comment]
OK, I compiled it myself. Where's the PKGBUILD for the package `vdr-vnsiserver` though? I can't find it...

**Comment by jlp2** [comment]
You mean the plugin for the vdr? Look at vdr4arch/plugins/vdr-vnsiserver/...
The plugin for Kodi you find at vdr4arch/kodi-addon-pvr-vdr-vnsi/

**Comment by jansohn** [comment]
Yes, the plugin was what I was looking for! Should I close this issue or leave it open because of the "auto-update" via AUR?

**Comment by jlp2** [comment]
May you leave it open, i think the status quo is not very comfortable for the users of vdr4arch at the moment.

@M-Reimer Are there any possibilitys to help?
Yesterday i have a look into the PKGBUILD's of some Packages. For example the vdr-build is not actual, there is a new diff in ftp://ftp.tvdr.de/vdr/Developer/Patches/vdr-2.4 (vdr-2.4.0-07-fix-disabling-mtd.diff) that is not in the PKGBUILD.
Also the vdr-vnsiserver is behind the git of FernetMenta (vdr4arch:1.6 vs. 1.8 in FernetMenta'git)
I just checked a few PKGBUILD's cause I'm using the vdr just as a backend for kodi.

Don't know if this patches are important, or if they break some other things, but mostly Arch follows upstream closer..
Maybe we could help to keep this git more actual?

**Comment by M-Reimer** [comment]
I have the script, that was used so far.
I'll rewrite most of it as I think using "shallow copies" from AUR would simplify some things.
And I'll wait for Kodi 18 to get released so I can merge back the "kodi 18" branch first.

**Comment by M-Reimer** [comment]
AUR sync is done. I've cleaned up the sync script and uploaded it to the vdr4arch repository, in case some other project also wants to handle many PKGBUILDs in one single GIT repo.
