### ISSUE TITLE
TVGuide 1.29 released

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#210]
https://projects.vdr-developer.org/git/vdr-plugin-tvguide.git

**Comment by M-Reimer** [comment]
Can you create a pull request for this? Don't forget to include .SRCINFO and do a test build.

**Comment by utiltiy** [comment]
I don't use GIT and my PKBUILD in my virtual build system are diffrent, sorry.

The build is ok, here

**Comment by CReimer** [comment]
Done
