### ISSUE TITLE
new chance for softhddevice

### ISSUE THREAD

**Issue by berndbb** [VDR4Arch/vdr4arch#212]
As discussed here:
https://www.vdr-portal.de/forum/index.php?thread/132343-vdr4arch-pkgbuilds-werden-jetzt-ins-aur-synchronisiert-vorerst-keine-bin%C3%A4rpakete/&postID=1319352#post1319352

I humbly suggest to give these sources a chance:
https://github.com/ua0lnj/vdr-plugin-softhddevice

At least I think a managed to compile them on my arch-pc against recent ffmpeg and I get live-TV, access to osd using the built in gpu of a AMD Ryzen 5000 CPU and vdpau for decoding.

Kind regards
bernd_b

**Comment by CReimer** [comment]
With some cross-referencing with vdr-portal I figured out which sources @berndbb is referring to: https://github.com/ua0lnj/vdr-plugin-softhddevice

**Comment by berndbb** [comment]
Sorry, the links were broken ...

**Comment by M-Reimer** [comment]
Fixed in https://github.com/VDR4Arch/vdr4arch/commit/2efa068ae92375df3f34331db1a22b123517c06d
