### ISSUE TITLE
w_scan upstream is dead

### ISSUE THREAD

**Issue by kaffeekanne** [VDR4Arch/vdr4arch#215]
w_scan is abandoned, i think, and the upstream url is not valid anymore. For this package to build from AUR a new source would be needed, any ideas? 

There are forks called [w_scan2](https://github.com/stefantalpalaru/w_scan2) and [t2scan](https://github.com/mighty-p/t2scan) but i did not try them out yet.

**Comment by M-Reimer** [comment]
Found it: https://www.gen2vdr.de/wirbel/w_scan/index2.html
So "url" and "source" would need to be updated.
I would fix this as soon as possible so it builds again. But: I can't sync this one to AUR as I'm not maintainer for this one on AUR. You either have to build from our GIT or use our auto-built binaries.

**Comment by M-Reimer** [comment]
PKGBUILD fixed.
