### ISSUE TITLE
vdrpbd

### ISSUE THREAD

**Issue by utiltiy** [VDR4Arch/vdr4arch#216]
PKGBUILD für aktuelle Version, da nicht mit Tag versehen:

`# This PKGBUILD is part of the VDR4Arch project [https://github.com/vdr4arch]

# Maintainer: Manuel Reimer <manuel.reimer@gmx.de>
pkgname=vdrpbd
pkgver=2.0.1
_gitver=a4546d3fcad1b8b171415fd99928a920de5ee0a6
pkgrel=1
pkgdesc="A daemon to handle ACPI power button event on VDR systems"
url="http://projects.vdr-developer.org/projects/vdrpbd"
arch=('any')
license=('GPL3')
depends=('perl-net-dbus')
makedepends=('perl')
backup=('etc/vdrpbd.conf')
source=("git://projects.vdr-developer.org/vdrpbd.git#commit=$_gitver")
md5sums=('SKIP')

pkgver() {
  cd "$srcdir/$pkgname"
  git describe --tags | sed 's/-/_/g;s/v//'
}

prepare() {
  cd "$srcdir/$pkgname"
}

package() {
  cd "$srcdir/$pkgname"
  make BINDIR=/usr/bin DESTDIR="$pkgdir" PREFIX=/usr  install
}
`

**Comment by M-Reimer** [comment]
"Abgelehnt" :stuck_out_tongue: 

Ist im GIT sauber getaggt. Downloads (auch tarballs) gibt es hier:
https://projects.vdr-developer.org/git/vdrpbd.git/

Die "projects.vdr-developer.org"-Seite werde ich nicht mehr aktualisieren. Eher würde ich die dort noch stehenden Dateien bei Gelegenheit alle löschen.

Ein auf oben genannte Tarballs angepasstes PKGBUILD würde ich aber gerne als Pull-Request übernehmen.

**Comment by M-Reimer** [comment]
Nachtrag: Hiermit geschehen. Alle Dateien auf der Projektseite sind gelöscht. Downloads gibt es auf oben verlinkter GIT-Seite.

**Comment by utiltiy** [comment]
Wenn jemand hier sucht: https://projects.vdr-developer.org/projects/vdrpbd/repository findet er nichts. Früher wurde das mal ordentlich gepflegt, jetzt macht scheinbar jeder wie er mag.

**Comment by utiltiy** [comment]
Ich lass mein lokales PKGBUILD so, ist mir lieber so, mit den GIT Versionen.

**Comment by M-Reimer** [comment]
Ganz ehrlich: Ich hab keine Zeit für Wildwuchs.

Um das auf projects.vdr-developer.org rein zu bekommen muss ich manuell ein tarball erzeugen, mich dort einloggen und das manuell hochladen. Zuviel Aufwand: Durchgefallen.

Für die Git Seite von projects.vdr-developer.org reicht, wie bei GitHub, ein GIT Tag.

Bevor ich das bei projects.vdr-developer.org korrekt pflege fliegt es dort komplett runter und wird auf meinen GitHub Account umgezogen.

**Comment by utiltiy** [comment]
Darfst Händeln wie du willst.

**Comment by M-Reimer** [comment]
PKGBUILD ist jetzt hier und im AUR aktuell.
Den Link zu den Dateien konnte ich im Redmine sogar ganz deaktivieren.
Ein Link auf die Downloads der Release-Dateien gibt es jetzt direkt hier:
https://projects.vdr-developer.org/projects/vdrpbd
