### ISSUE TITLE
VDR-Prozess bleibt beim "systemctl stop vdr.service" hängen und zerstört die setup.conf

### ISSUE THREAD

**Issue by mcl2009** [VDR4Arch/vdr4arch#220]
Hallo allerseits,

ich habe seit dem Wechsel auf vdr 2.4.1 ein sehr komisches Problem: Ein stop des VDR-Prozesses führt oft zu einer offensichtlich zerstörten setup.conf. 

Ablauf:

systemctl stop vdr.service
=> lange Wartezeit
=> VDR startet wieder, IR-Bedienung geht nicht mehr
Lösung => löschen von setup.conf, kill -9 vdr, dann startet er neu. Bedienung über Lirc geht wieder

Ich kann den Fehler einfach nicht greifen. Manchmal läuft das über Tage gut, dann wiederrum passiert was, oft beim wechseln von Kodi zurück zum VDR. Dann ist die Bedienung wieder unmöglich und ich muss o.g. "Lösung" anwenden.

Bitte um Hilfe & VG
Matthias

**Comment by M-Reimer** [comment]
Sorry aber hier wird dir eher keiner helfen können.

Bitte stelle das Thema im VDR-Portal zur Diskussion und packe einen Link hier rein.

Ich nutze den VDR ausschließlich als Backend rein mit Kodi Clients favor. Die Art und Weise wie der VDR auf Grafikkarten die Ausgabe macht ist "suboptimal". Es wäre schöner hier eine Trennung zwischen Backend und Frontend zu haben.

**Comment by mcl2009** [comment]
Danke für die schnelle Antwort. Das Thema ist schon eine Weile im Forum eingestellt:

https://www.vdr-portal.de/forum/index.php?thread/133295-vdr4arch-und-vdr-2-4-1-nach-erstem-speichern-der-setup-conf-funktioniert-lirc-ni/

Ich schließe das hier.

**Comment by M-Reimer** [comment]
Nachtrag: Ist mittlerweile dank des Patches von seahawk1986 gefixt und sollte jetzt eigentlich ohne Fehler zu beenden sein.
