### ISSUE TITLE
vdrpbd: Service startet nicht

### ISSUE THREAD

**Issue by jlp2** [VDR4Arch/vdr4arch#223]
vdrpbd gibt nach dem starten durch systemd, aber auch manuell via "vdrpbd -f" folgende Fehlermeldung aus:
```
Can't locate Pod/PlainText.pm in @INC (you may need to install the Pod::PlainText module) (@INC contains: /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/perl5/core_perl) at /usr/bin/vdrpbd line 19.
BEGIN failed--compilation aborted at /usr/bin/vdrpbd line 19.
```
```
systemctl status vdrpbd
● vdrpbd.service - VDR ACPI power button handling daemon
     Loaded: loaded (/usr/lib/systemd/system/vdrpbd.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2020-08-11 13:20:44 CEST; 36s ago
    Process: 340 ExecStart=/usr/sbin/vdrpbd -f (code=exited, status=2)
   Main PID: 340 (code=exited, status=2)

Aug 11 13:20:44 server.fritz.box systemd[1]: Started VDR ACPI power button handling daemon.
Aug 11 13:20:44 server.fritz.box vdrpbd[340]: Can't locate Pod/PlainText.pm in @INC (you may need to install the Pod::PlainText module) (@INC contains: /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/p>
Aug 11 13:20:44 server.fritz.box vdrpbd[340]: BEGIN failed--compilation aborted at /usr/sbin/vdrpbd line 19.
Aug 11 13:20:44 server.fritz.box systemd[1]: vdrpbd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 11 13:20:44 server.fritz.box systemd[1]: vdrpbd.service: Failed with result 'exit-code'.
```

**Comment by M-Reimer** [comment]
This is a known problem but so far it didn't bother me as I've just disabled vdrpbd on my HTPC. Kodi doesn't need it anyway. Again: vdrpbd is a separate project which is maintained here:

https://projects.vdr-developer.org/projects/vdrpbd

To fix this I have to rework the help message generation. I already did this for repo-make and just have to port the fix back to vdrpbd as soon as I find the time.

**Comment by jlp2** [comment]
> This is a known problem but so far it didn't bother me as I've just disabled vdrpbd on my HTPC. Kodi doesn't need it anyway.

I see what you mean.
Unfortunately I use separate Kodi-Boxes (Intel NUC) and an extra server with vdr.
The vdr regulates the power management on this server and so that you don't accidentally switch it off when recordings are still running, vdrpd was an excellent fit.

> To fix this I have to rework the help message generation. I already did this for repo-make and just have to port the fix back to vdrpbd as soon as I find the time.

Thats would be great. Thank you for your effort!

**Comment by jlp2** [comment]
> I already did this for repo-make...

I found your rework for the message generation in repo-makeand tried to fix the vdrpbd file in the same manner.
```
@@ -16,7 +16,7 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 use strict;
-use Pod::Simple::Text;
+use Pod::PlainText;
 use Getopt::Std;
 use POSIX;
 use threads;
@@ -152,7 +152,7 @@
 
 sub HELP_MESSAGE {
   # Print out the built-in POD documentation in case of --help parameter
-  Pod::Simple::Text->filter($0);
+  Pod::PlainText->new(sentence => 0)->parse_from_file($0);
 }
 
 sub ParseConfig {
```
I don't really have any idea what I was doing, but vdrpbd started and worked after that.
Unfortunately I don't know how to submit patches to https://projects.vdr-developer.org/projects/vdrpbd, so I'll post it here now.

**Comment by M-Reimer** [comment]
Future issues about vdrpbd can be reported here:

https://github.com/M-Reimer/vdrpbd/issues

I've also disabled the issue tracker on projects.vdr-developer.org as it is more convenient to have all my issues tracked at the same hosting platform.
