### ISSUE TITLE
vdr-satip does not compile

### ISSUE THREAD

**Issue by nafets227** [VDR4Arch/vdr4arch#227]
http://www.saunalahti.fi/~rahrenbe/vdr/satip/files/vdr-satip-2.4.0.tgz cannot be accessed.
Maybe better to download from GitHub at https://github.com/rofafor/vdr-plugin-satip/archive/v2.4.0.tar.gz ?

**Comment by M-Reimer** [comment]
Thanks for reporting.
This affects all @rofafor plugins so I changed the source for them all to point to GitHub.
The binary repository is already up-to-date. Sync to AUR currently running.
