### ISSUE TITLE
[vdr-live] new version available and dependencies problem

### ISSUE THREAD

**Issue by lapicidae** [VDR4Arch/vdr4arch#231]
vdr-live-3.1.3 is online since 14 Nov
[vdr-live-3.1.3_PKGBUILD.patch.txt](https://github.com/VDR4Arch/vdr4arch/files/7743635/vdr-live-3.1.3_PKGBUILD.patch.txt)

I want to build via AUR but:
The source and upstream URLs of the cxxtools and tntnet deps packages are offline but github ist working.
[cxxtools AUR](https://aur.archlinux.org/packages/cxxtools) is maintained by another user... I contacted him.
[tntnet-3.0_PKGBUILD.patch.txt](https://github.com/VDR4Arch/vdr4arch/files/7743743/tntnet-3.0_PKGBUILD.patch.txt)

**Comment by M-Reimer** [comment]
If the current maintainer of cxxtools does not react, I could try to adopt this package and link it to my sync script. I maintain my own version anyway: https://github.com/VDR4Arch/vdr4arch/tree/master/deps/cxxtools

All the other ones should be up to date now. Thanks for the report.

**Comment by lapicidae** [comment]
No answer from the cxxtools maintainer.
Could you try to adopt this package in AUR?

Thanks!

**Comment by M-Reimer** [comment]
I'll wait some more days. Probably not the time to expect quick reaction times.
