### ISSUE TITLE
[vdr-ddci2] change vdr-api version

### ISSUE THREAD

**Issue by lapicidae** [VDR4Arch/vdr4arch#232]
ddci2 works fine with my version 2.4.7 VDR, could you change the api version?

**Comment by lapicidae** [comment]
I meant the "vdrapi" version:

    -_vdrapi=2.4.6
    +_vdrapi=2.4.7

**Comment by M-Reimer** [comment]
I know. Just have to find the time to check this myself. I'm unsure why I removed this package from the autobuild process.
