### ISSUE TITLE
[vdr-channelscan] installation problem

### ISSUE THREAD

**Issue by lapicidae** [VDR4Arch/vdr4arch#233]
The plugin will not be fully installed if a supplied configuration file exists in "/var/lib/vdr/plugins/channelscan/".
```
mkdir -p /var/lib/vdr/plugins/channelscan $$ touch /var/lib/vdr/plugins/channelscan/Sat.ini
pacman -S --noconfirm vdr-channelscan

vdr-channelscan: /var/lib/vdr/plugins/channelscan/Sat.ini exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by M-Reimer** [comment]
I've asked in vdr-portal and also got feedback from the developer, as I don't use this plugin:

https://www.vdr-portal.de/forum/index.php?thread/134874-frage-zu-plugin-vdr-channelscan-wie-vorgehen-mit-sat-ini-beim-paketieren/

All these files should be in the "backup" array. I've fixed that. But you will still get this error. There is nothing I can do about this. Have a look at the man-page of "pacman". There should be some parameter in there which allows to overwrite the file.
