### ISSUE TITLE
vdr-plugin-robotv

### ISSUE THREAD

**Issue by romrich** [VDR4Arch/vdr4arch#244]
### Name of the software, you want to be added to vdr4arch.

vdr-plugin-robotv

### URL of the project page.

https://github.com/pipelka/vdr-plugin-robotv/

### Additional information

If someone creates PKGBUILD I can try to test it.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/VDR4Arch/vdr4arch/issues)
- [X] I accept being responsible for testing the prepared PKGBUILD.

**Comment by M-Reimer** [comment]
PKGBUILD prepared here:
https://github.com/VDR4Arch/vdr4arch/tree/vdr-robotv/plugins/vdr-robotv
It does build and at least as far as I can understand all files are installed where they should be.

**Comment by M-Reimer** [comment]
Do you still need something to test the PKGBUILD? You should be able to just clone the branch "vdr-robotv" and test from that.

**Comment by M-Reimer** [comment]
Still interested in getting this merged? Adding a "helpwanted" now. Maybe someone else wants to try this out. I'll no longer update the "vdr-robotv" branch, now.

**Comment by M-Reimer** [comment]
No feedback after around one year despite accepting to test the resulting PKGBUILD.
Congratulations, all future Issues, opened by you, will be closed immediately as "not planned" :tada: 

As, in fact, many (if not most) plugin PKGBUILDs are untested here, I've added the untested PKGBUILD, now.
