### ISSUE TITLE
vdr-softhddrem (part of vdr-softhdcuvid) does not build on raspberry Pi 5

### ISSUE THREAD

**Issue by nafets227** [VDR4Arch/vdr4arch#250]
### Describe the problem

If executing AUR build on Raspberry Pi 5 it fails due to missing dependency on nvidia.

### To reproduce

See https://github.com/nafets227/archPackages/actions/runs/8491942107/job/23264426846

### Expected behavior

Build compiled ok

### Additional context

Possible solution see 
https://github.com/nafets227/vdr-softhdcuvid.aur/commit/394f1cb3acdd0ece35e69bf4180b5f5479abfc5b

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/VDR4Arch/vdr4arch/issues)
- [X] My report contains all necessary details

**Comment by M-Reimer** [comment]
Please create a Pull Request from that. Thanks.

**Comment by M-Reimer** [comment]
Thank you for your contribution.

**Comment by nafets227** [comment]
Welcome, when do you plan to update AUR?

**Comment by M-Reimer** [comment]
AUR will always be second place as I can't update it from my phone and I myself don't use AUR as I auto-build a full repo.

But I did just run the sync script, so AUR is up to date, now.

**Comment by nafets227** [comment]
thanks a lot!
