### ISSUE TITLE
Oscam-smod pkgbuild

### ISSUE THREAD

**Issue by sgmihai** [VDR4Arch/vdr4arch#253]
### Name of the software, you want to be added to vdr4arch.

Oscam-smod

### URL of the project page.

https://github.com/Schimmelreiter/oscam-smod

### Additional information

I always used https://github.com/Schimmelreiter/oscam-smod because of its nice themes, included oscam-emu. Also has some auto config for "many cards" but I don't know anything about that.
I managed to put together a pkgbuild  based on the aur oscam-git one, which apparently is based on the one in this repo. But I had trouble with the build step and I don't think what I figured out back then is not proper. Link: https://pastebin.com/raw/QRwS0k5k
Please take a look and consider making a proper PKGBUILD and add it to the repo

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/VDR4Arch/vdr4arch/issues)
- [X] I accept being responsible for testing the prepared PKGBUILD.

**Comment by M-Reimer** [comment]
This is likely out of scope here.

Does not seem to be related to VDR.

**Comment by sgmihai** [comment]
oscam already has a PKGBUILD here, don't see how an improved distribution of it (feature patch, embedded configs for devices, and themes) would be out of scope.

**Comment by M-Reimer** [comment]
The "improved distribution" of it didn't see any updates for 10 months while "original oscam" is updated regularly.

In fact even oscam itself is "more or less" out of scope here. If you compare with AUR, you'll see that the oscam PKGBUILD here is not synced over to AUR by intention. It is only here to simplify automatic binary repository creation including a build of oscam.

Yes, someone seems to have taken the PKGBUILD from here to base a "-git" package from it. The author of this PKGBUILD was nice and kept credit for vdr4arch but the PKGBUILD you find on AUR is not maintained here.

I am not interested in creating an oscam-smod PKGBUILD. It is not needed here and I don't want to maintain it on AUR.

**Comment by M-Reimer** [comment]
As you seem to search for help with getting oscam-smod packaged, this may be the correct place to ask for help: https://bbs.archlinux.org/viewforum.php?id=38

Hope this helps. 👍

**Comment by M-Reimer** [comment]
The oscam PKGBUILD, which was here on GIT, is now gone also.
