### ISSUE TITLE
vdr startet zu früh

### ISSUE THREAD

**Issue by HTPC-Schrauber** [VDR4Arch/vdr4arch#65]
Hallo,

ich hatte gestern nach einem Update (mein Systemstand war schon recht alt) das Problem, das der VDR gestartet wurde, bevor Udev die Gruppenrechte an den DVB-Devices richtig gesetzt hatte. Dadurch kam der VDR nicht an die Device dran. Das Ganze klappte manchmal und manchmal nicht. Also offenbar zeitlich sehr knapp beieinander.

Gelöst habe ich das, indem  ich dem VDR Service noch ein:
wants=systemd-udev-trigger.service
after=systemd-udev-trigger.service

hinzugefügt habe. Das hat jetzt jedenfalls über mehrere Neustarts funktioniert.

Vielleicht sollte das in das Paket mit einfließen.

Grüße

**Comment by HTPC-Schrauber** [comment]
Habt Ihr das Script wieder ausgebaut?
Auf meinem neu aufgesetzten Server startet der VDR nämlich wieder zu früh und ich konnte das Script nicht mehr finden.

Oder sollte VDR das inzwischen selbst können?

**Comment by CReimer** [comment]
Du musst auch die Meldungen lesen, die beim Update bzw. Installieren angezeigt werden.

Starte vdr-gensddropin

**Comment by HTPC-Schrauber** [comment]
Hmmpf, tu ich normalerweise. Die Meldung ist mir aber nicht aufgefallen.
Wie auch immer, konnte dann nicht funktionieren, wenn es nur beim Installieren ausgeführt wird. Das war dir DVB-Karte noch nicht drin.

Das Script hab ich jetzt auch wiedergefunden.
