### ISSUE TITLE
xineliboutput libcec support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#84]
Hello again,

today I'm trying to get the CEC interface working between RPi and my TV. First let me tell you that I've tryed already it with OpenELEC and Kodi on Arch, and it works out of the box.

But what I'm trying to do now is building a custom configuration working entirely and only with VDR. So I'm using `xineliboutput` with this config:

```bash
[xineliboutput]
--local=fbfe
--remote=none
--audio=auto
--video=fb
--fullscreen
```

Now what I'm trying to do is that I would like to add the option `--cec` coming from `vdr-fbfe`. But what I get from Arch is

```bash
vdr[366]: xineliboutput: unrecognized option '--cec'
```

actually `vdr-fbfe` supports it:

```zsh
~ # vdr-fbfe --help | grep CEC
   -E, --nocec                   Disable HDMI-CEC input device
   -e, --cec[=port[,type]]       Use HDMI-CEC input device
```

What should I do to just add that option to `vdr-fbfe`?

**Comment by CReimer** [comment]
This seems to be an upstream bug as libcec support ist enabled in vdr4arch's xineliboutput package.

Please report this http://sourceforge.net/p/xineliboutput/bugs/

**Comment by CReimer** [comment]
Wait. There's actually something wrong with the xineliboutput-frontends package on ARM. I'll look into this.

**Comment by julianxhokaxhiu** [comment]
Thank you :)

**Comment by julianxhokaxhiu** [comment]
Since I'm no more using xineliboutput you can just drop this issue.
