### ISSUE TITLE
OSCAM rebuild

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#86]
Can you please rebuild OSCAM package using the latest commits?

http://www.streamboard.tv/svn/svnstyle/open/log/?base=oscam&target=/trunk

Thanks in advice :)

**Comment by CReimer** [comment]
It up to date in the testing branch now.

vdr4arch-stable is frozen until next Sunday (one week delay after a new VDR version). Further updates until then will go to the testing repository.
There are more infos about this policy in the README
