### ISSUE TITLE
vdr-rpihddevice 0.0.11

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#88]
Hi,

can you upgrade the package to this version? :)

Thanks in advice,
Julian

**Comment by CReimer** [comment]
There's nothing different than in the version currently in the repos.

We are exactly one revision behind 0.0.11: http://projects.vdr-developer.org/git/vdr-plugin-rpihddevice.git/commit/?id=d0924443ed4eef68f9cac6ac7cbda8fc4d63b31e

And the latest commit only changes the version strings. I will update the package later today, but there's nothing different except the version string.
