### ISSUE TITLE
[vdr-eepg] segfaults -> update fixes

### ISSUE THREAD

**Issue by mafe** [VDR4Arch/vdr4arch#92]
vdr-eepg _gitver=69b47ba4bf0195fd6820beb2cf4f7c7ea31f4011 does segfault on my vdr.
The latest from master
_gitver=d7dc6141c91b48c410e9cc5734ca9a2adecc278e
does work.
Would you update PKGBUILD please?

**Comment by CReimer** [comment]
Package is now up to date
