### ISSUE TITLE
Could you provide saa716x support for arch?

### ISSUE THREAD

**Issue by zofiel** [VDR4Arch/vdr4arch#97]
Saa716x driver: https://github.com/ljalves/linux_media/tree/latest/drivers/media/pci/saa716x

Could you include it in your driver repository?

Thanks in advance

**Comment by CReimer** [comment]
This driver is already part of media_build_experimental-dkms

I know that this dkms package is broken at the moment. But that's a problem which Oliver Endriss has to fix (maintainer of media_build_experimental).
I'm still waiting for him to fix this.

Where did you find Luis Alves' the repository? What's his ultimate goal?

Nevertheless I don't think it's right to just randomly add more driver packages. These drivers have to end in an upstream kernel anytime soon.

**Comment by CReimer** [comment]
I asked him to add the Digital Devices drivers. If he does so or accepts a pull request his repo could become a suitable replacement for media_build_experimental.

**Comment by zofiel** [comment]
I found It in the v4l wiki: http://www.linuxtv.org/wiki/index.php/NXP_SAA716x

thanks for all Creimer.
