### ISSUE TITLE
epgd:  Failed to start Database driven EPG Data collector.

### ISSUE THREAD

**Issue by zofiel** [VDR4Arch/vdr4arch#98]
MYSQL: Mariadb

install following packages (in order)

epgd
mariadb-epglv

systemctl status: 
 epgd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since jue 2015-05-21 11:51:37 CEST; 11min ago

may 21 11:51:37 pcsalon systemd[1]: Starting Database driven EPG Data collector...
may 21 11:51:37 pcsalon systemd[1]: epgd.service: control process exited, code=exited status=203
may 21 11:51:37 pcsalon systemd[1]: Failed to start Database driven EPG Data collector.
may 21 11:51:37 pcsalon systemd[1]: Unit epgd.service entered failed state.
may 21 11:51:37 pcsalon systemd[1]: epgd.service failed.

Journal:

Unit epgd.service has begun starting up.
may 21 11:51:37 pcsalon systemd[17637]: Failed at step EXEC spawning /usr/bin/epgd: No such file or directory
-- Subject: Process /usr/bin/epgd could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/bin/epgd could not be executed and failed.

I checked and no usr/bin/epgd file found. reinstall epgd and this error dissapear

 Failed at step EXEC spawning /usr/bin/epgd: No such file or directory

but epgd service doesn't load.

I followed this guide using your owns packages:

http://projects.vdr-developer.org/projects/vdr-epg-daemon/wiki

thanks in advance

**Comment by CReimer** [comment]
/usr/bin/epgd is part of the epgd package on all supported architectures.
and there's no install script which could affect /usr/bin/epgd.
